### ISSUE TITLE
pybind11 오류

### ISSUE THREAD

**Issue by hongsukpyo** [jonghwanhyeon/python-mecab-ko#14]
안녕하세요?
설치 후, 테스트를 해보니 아래와 같이 pybind11 type error 발생하는데 도움을 주실 수 있으실까요?
pybind11 은 pybind11-2.7.1-py2.py3-none-any.whl 을 다운 받아 설치 하였습니다.

>import mecab
>m=mecab.MeCab()
,,,,,,,,,,,, /mecab/mecab.py in __init__.py(self, dicpath)
51          argument = '-d %s' % dicpath
52
53     self.tagger = _mecab.Tagger(argument)
54
55  def parse(self, sentence):

TypeError: pybind11::init()Lfactory function returned nullptr

**Comment by mkjames98** [comment]
해당 오류 혹시 어떻게 고치셨나요?

**Comment by dan-rtzr** [comment]
@hongsukpyo 저도 같은 에러가 나는데요 혹시 어떻게 해결하셨나요?
