### ISSUE TITLE
python 패키지 설치 시, 시스템 라이브러리(mecab-ko) 설치는 권장되지 않습니다.

### ISSUE THREAD

**Issue by Seunghan-Jung** [jonghwanhyeon/python-mecab-ko#18]
https://github.com/jonghwanhyeon/python-mecab-ko/blob/5af8335324b6f3c3cc851ea39fb21716dcc8343c/setup.py#L49-L52
해당 패키지 설치시, 시스템 라이브러리 mecab-ko에 대한 설치도 유도되고 있는데요.

이는 권장되지 않는 방식으로 시스템 라이브러리 설치는 따로 분리하여 별도로 실행할 수 있도록 하는 것이 좋겠습니다.

보안 문제가 있을 수 있으며, 이미 해당 시스템 라이브러리가 설치 되어 있는 장치에서는 충돌이 발생할 수 있습니다. (`mecab-config` 명령어를 통해서 설치여부를 확인하나 사용자가 PATH에 (의도했든 안 했든) 등록 안 했을 수 있습니다.)

**Comment by jonghwanhyeon** [comment]
`setup.py`에서 해당 부분 삭제 완료하였습니다. 아마도, 대부분의 사용자는 이미 mecab-ko가 링크된 wheel 배포 버전을 사용해 설치를 수행하여 해당 메시지를 볼 기회는 적었을 것이라 예상됩니다.
